version: "3.7"

services:

  flare:
    ports:
      - ${PORT_FLARE:-127.0.0.1:5000}:5000
    environment:
      FHIR_BASE_URL: ${FHIR_BASE_URL:-http://fhir-server:8080/fhir}
      DEBUG: ${FLARE_DEBUG:---debug}
    build: .
    restart: always
    volumes:
      - ./src:/opt/flare/src
      - ${CODEX_CONCEPT_TREE_PATH:-./src/query_parser/codex/codex-code-tree.json}:/opt/flare/src/query_parser/codex/codex-code-tree.json
      - ${CODEX_TERM_CODE_MAPPING_PATH:-./src/query_parser/codex/codex-mapping.json}:/opt/flare/src/query_parser/codex/codex-mapping.json

  fhir-server:
    image: ghcr.io/chgl/hapifhir/hapi-fhir-jpaserver-starter:v5.4.0-distroless
    restart: always
    ports:
      - ${PORT_HAPI_FHIR:-127.0.0.1:8081}:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      VALIDATION_REQUESTS_ENABLED: "false"
      HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY: "true"
    depends_on:
      - db

  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
